server:
  port: 8888

xdiamond:
  client:
    groupid: com.chen
    artifactid: clientdemo
    version: 0.0.1-SNAPSHOT
    profile: dev
    secretkey: 123456
  server:
    host: localhost
    port: 5678
